version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - cashflow-network

  launch-service:
    build: ./launch-service
    container_name: launch-service
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - cashflow-network
  # consolidacao-service:
  #   build: ./consolidacao-service
  #   ports:
  #     - "3002:3002"
  #   depends_on:
  #     - launch-service
  #   networks:
  #     - cashflow-network

networks:
  cashflow-network:
    driver: bridge
